In [1]:
import pandas as pd

In [2]:
import numpy as np

### Andmetöötluse prototüüpimine

Võtan aluseks juhendis öeldud *featrue*-id:
  * Price - geoplaces
  * Parking - chefmozparking
  * Smoking Area - geoplaces
  * Other Services - geoplaces
  * Dress Code - geoplaces
  * Accessibility - geoplaces

In [3]:
geoplaces = pd.read_csv("../data/geoplaces2.csv", index_col=0)
geoplaces.head()

,latitude,longitude,the_geom_meter,name,address,city,state,country,fax,zip,alcohol,smoking_area,dress_code,accessibility,price,url,Rambience,franchise,area,other_services
placeID,,,,,,,,,,,,,,,,,,,,
134999,18.915421,-99.184871,0101000020957F000088568DE356715AC138C0A525FC46...,Kiku Cuernavaca,Revolucion,Cuernavaca,Morelos,Mexico,?,?,No_Alcohol_Served,none,informal,no_accessibility,medium,kikucuernavaca.com.mx,familiar,f,closed,none
132825,22.147392,-100.983092,0101000020957F00001AD016568C4858C1243261274BA5...,puesto de tacos,esquina santos degollado y leon guzman,s.l.p.,s.l.p.,mexico,?,78280,No_Alcohol_Served,none,informal,completely,low,?,familiar,f,open,none
135106,22.149709,-100.976093,0101000020957F0000649D6F21634858C119AE9BF528A3...,El Rinc�n de San Francisco,Universidad 169,San Luis Potosi,San Luis Potosi,Mexico,?,78000,Wine-Beer,only at bar,informal,partially,medium,?,familiar,f,open,none
132667,23.752697,-99.163359,0101000020957F00005D67BCDDED8157C1222A2DC8D84D...,little pizza Emilio Portes Gil,calle emilio portes gil,victoria,tamaulipas,?,?,?,No_Alcohol_Served,none,informal,completely,low,?,familiar,t,closed,none
132613,23.752903,-99.165076,0101000020957F00008EBA2D06DC8157C194E03B7B504E...,carnitas_mata,lic. Emilio portes gil,victoria,Tamaulipas,Mexico,?,?,No_Alcohol_Served,permitted,informal,completely,medium,?,familiar,t,closed,none

In [4]:
geoplaces.size

2600

`geoplaces`-ist võtta andmed:
  * `smoking_area`
  * `other_services`
  * `dress_code`
  * `accessibility`
  
Nende kõigi puhul peaks vaatama mis väärtused on võimalikud:

In [5]:
geoplaces = pd.DataFrame(geoplaces, columns=["smoking_area", "other_services", "dress_code", "accessibility"])

In [6]:
geoplaces.smoking_area.unique()

array(['none', 'only at bar', 'permitted', 'section', 'not permitted'], dtype=object)

`smoking_area` peaks proovima mõlemat moodi, nii one hot-iga kui labelencoderiga

In [7]:
geoplaces.other_services.unique()

array(['none', 'Internet', 'variety'], dtype=object)

`other_services` peaks one hot encode-ima

In [8]:
geoplaces.dress_code.unique()

array(['informal', 'casual', 'formal'], dtype=object)

In [9]:
geoplaces.accessibility.unique()

array(['no_accessibility', 'completely', 'partially'], dtype=object)

`accessibility` peaks labelencodima

`parking` tabelist ainult parkimise data

In [10]:
parking = pd.read_csv("../data/chefmozparking.csv", index_col=0)
parking.head()

        parking_lot
placeID
135111       public
135110         none
135109         none
135108         none
135107         none

In [11]:
len(parking)

702

In [12]:
parking.parking_lot.unique()

array(['public', 'none', 'yes', 'valet parking', 'fee', 'street',
       'validated parking'], dtype=object)

`parking_lot`-i andmed saab kodeerida one hot encoderiga

In [13]:
ratings = pd.read_csv("../data/rating_final.csv")
ratings = ratings.drop(["food_rating","service_rating"], axis=1)

In [14]:
ratings.rating.unique()

array([2, 1, 0], dtype=int64)

In [15]:
len(ratings)

1161

In [16]:
ratings

     userID  placeID  rating
0     U1077   135085       2
1     U1077   135038       2
2     U1077   132825       2
3     U1077   135060       1
4     U1068   135104       1
5     U1068   132740       0
6     U1068   132663       1
7     U1068   132732       0
8     U1068   132630       1
9     U1067   132584       2
10    U1067   132733       1
11    U1067   132732       1
12    U1067   132630       1
13    U1067   135104       0
14    U1067   132560       1
15    U1103   132584       1
16    U1103   132732       0
17    U1103   132630       1
18    U1103   132613       2
19    U1103   132667       1
20    U1103   135104       1
21    U1103   132663       1
22    U1103   132733       2
23    U1107   132660       2
24    U1107   132584       2
25    U1107   132733       2
26    U1044   135088       2
27    U1044   132583       1
28    U1070   132608       2
29    U1070   132609       1
...     ...      ...     ...
1131  U1087   132732       2
1132  U1087   132740       1
1133  U1087   132560       1
1134  U1087   132594       1
1135  U1087   132663       1
1136  U1065   132626       1
1137  U1065   132706       2
1138  U1129   132561       1
1139  U1065   132665       1
1140  U1129   132665       0
1141  U1065   132561       1
1142  U1039   132626       2
1143  U1039   132564       1
1144  U1065   132654       1
1145  U1039   132665       1
1146  U1130   132654       0
1147  U1130   132561       0
1148  U1130   132626       0
1149  U1130   132706       1
1150  U1043   132608       1
1151  U1043   132609       1
1152  U1011   132717       2
1153  U1043   132613       1
1154  U1011   132564       1
1155  U1043   132732       1
1156  U1043   132630       1
1157  U1011   132715       1
1158  U1068   132733       1
1159  U1068   132594       1
1160  U1068   132660       0

[1161 rows x 3 columns]

Edasine plaan:
  * Tabelid kokku panna (pandase merge-iga).
  * Vastavad featureextractionid teha.
  * Teha pipeline sklearninga ja ehitada mudel.
  * Mudeli uuesti ehitamine teha snakemake-il.
  * API jaoks teha esialgu mock mudel et oleks hea testida.

### Tabelite kokkupanek

Ratingud v2lja

In [17]:
df_ratings = ratings.set_index("placeID")[["rating"]]
df_ratings.head()

         rating
placeID
135085        2
135038        2
132825        2
135060        1
135104        1

In [18]:
df_ratings.size

1161

K6ik feature-id välja

In [19]:
df_features = geoplaces.join(parking)
df_features.head()

          smoking_area other_services dress_code     accessibility parking_lot
placeID
132560       permitted           none   informal  no_accessibility      public
132561            none           none   informal        completely        none
132564            none           none   informal        completely        none
132572   not permitted           none   informal        completely         yes
132583   not permitted           none   informal         partially        none

In [20]:
df = df_ratings.join(df_features)

`df` on lõplik feature-ite tabel. Selles konverteerin yleval tehtud märkmete järgi ümber osad feature-id.

In [21]:
df.head()

,rating,smoking_area,other_services,dress_code,accessibility,parking_lot
placeID,,,,,,
132560,1,permitted,none,informal,no_accessibility,public
132560,0,permitted,none,informal,no_accessibility,public
132560,0,permitted,none,informal,no_accessibility,public
132560,1,permitted,none,informal,no_accessibility,public
132561,1,none,none,informal,completely,none

In [22]:
df_smoking_area = pd.get_dummies(df.smoking_area, prefix="smoking_area")
df_smoking_area.head()

,smoking_area_none,smoking_area_not permitted,smoking_area_only at bar,smoking_area_permitted,smoking_area_section
placeID,,,,,
132560,0,0,0,1,0
132560,0,0,0,1,0
132560,0,0,0,1,0
132560,0,0,0,1,0
132561,1,0,0,0,0

In [23]:
df_other_services = pd.get_dummies(df.other_services, prefix="other_services")
df_other_services.head()

         other_services_Internet  other_services_none  other_services_variety
placeID
132560                         0                    1                       0
132560                         0                    1                       0
132560                         0                    1                       0
132560                         0                    1                       0
132561                         0                    1                       0

In [24]:
df_dress_code = pd.get_dummies(df.dress_code, prefix = "dress_code")
df_dress_code.head()

         dress_code_casual  dress_code_formal  dress_code_informal
placeID
132560                   0                  0                    1
132560                   0                  0                    1
132560                   0                  0                    1
132560                   0                  0                    1
132561                   0                  0                    1

In [25]:
df_accesibility = pd.get_dummies(df.accessibility, prefix="access")
df_accesibility.head()

         access__completely  access__no_accessibility  access__partially
placeID
132560                    0                         1                  0
132560                    0                         1                  0
132560                    0                         1                  0
132560                    0                         1                  0
132561                    1                         0                  0

In [26]:
df_parking_lot = pd.get_dummies(df.parking_lot, prefix = "parking")
df_parking_lot.head()

         parking_none  parking_public  parking_valet parking  parking_yes
placeID
132560              0               1                      0            0
132560              0               1                      0            0
132560              0               1                      0            0
132560              0               1                      0            0
132561              1               0                      0            0

In [27]:
df_encoded = pd.concat([df[["rating"]],
                        df_smoking_area,
                        df_other_services,
                        df_dress_code,
                        df_accesibility,
                        df_parking_lot
                      ],axis=1)

In [28]:
df_encoded

,rating,smoking_area_none,smoking_area_not permitted,smoking_area_only at bar,smoking_area_permitted,smoking_area_section,other_services_Internet,other_services_none,other_services_variety,dress_code_casual,dress_code_formal,dress_code_informal,access__completely,access__no_accessibility,access__partially,parking_none,parking_public,parking_valet parking,parking_yes
placeID,,,,,,,,,,,,,,,,,,,
132560,1,0,0,0,1,0,0,1,0,0,0,1,0,1,0,0,1,0,0
132560,0,0,0,0,1,0,0,1,0,0,0,1,0,1,0,0,1,0,0
132560,0,0,0,0,1,0,0,1,0,0,0,1,0,1,0,0,1,0,0
132560,1,0,0,0,1,0,0,1,0,0,0,1,0,1,0,0,1,0,0
132561,1,1,0,0,0,0,0,1,0,0,0,1,1,0,0,1,0,0,0
132561,1,1,0,0,0,0,0,1,0,0,0,1,1,0,0,1,0,0,0
132561,1,1,0,0,0,0,0,1,0,0,0,1,1,0,0,1,0,0,0
132561,0,1,0,0,0,0,0,1,0,0,0,1,1,0,0,1,0,0,0
132564,2,1,0,0,0,0,0,1,0,0,0,1,1,0,0,1,0,0,0
132564,1,1,0,0,0,0,0,1,0,0,0,1,1,0,0,1,0,0,0
132564,1,1,0,0,0,0,0,1,0,0,0,1,1,0,0,1,0,0,0
132564,1,1,0,0,0,0,0,1,0,0,0,1,1,0,0,1,0,0,0
132572,1,0,1,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,1
132572,2,0,1,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,1
132572,2,0,1,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,1
132572,0,0,1,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,1
132572,1,0,1,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,1
132572,1,0,1,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,1
132572,1,0,1,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,1
132572,2,0,1,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,1
132572,1,0,1,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,1
132572,1,0,1,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,1
132572,1,0,1,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,1
132572,1,0,1,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,1
132572,0,0,1,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,1
132572,1,0,1,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,1
132572,0,0,1,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,1
132583,1,0,1,0,0,0,0,1,0,0,0,1,0,0,1,1,0,0,0
132583,0,0,1,0,0,0,0,1,0,0,0,1,0,0,1,1,0,0,0
132583,1,0,1,0,0,0,0,1,0,0,0,1,0,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135104,1,0,1,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,1
135104,2,0,1,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,1
135104,1,0,1,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,1
135104,0,0,1,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,1
135104,1,0,1,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,1
135106,2,0,0,1,0,0,0,1,0,0,0,1,0,0,1,1,0,0,0
135106,2,0,0,1,0,0,0,1,0,0,0,1,0,0,1,1,0,0,0
135106,1,0,0,1,0,0,0,1,0,0,0,1,0,0,1,1,0,0,0
135106,2,0,0,1,0,0,0,1,0,0,0,1,0,0,1,1,0,0,0
135106,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,1,0,0,0
135106,2,0,0,1,0,0,0,1,0,0,0,1,0,0,1,1,0,0,0
135106,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,1,0,0,0
135106,0,0,0,1,0,0,0,1,0,0,0,1,0,0,1,1,0,0,0
135106,2,0,0,1,0,0,0,1,0,0,0,1,0,0,1,1,0,0,0
135106,1,0,0,1,0,0,0,1,0,0,0,1,0,0,1,1,0,0,0
135108,2,1,0,0,0,0,0,1,0,0,0,1,1,0,0,1,0,0,0
135108,2,1,0,0,0,0,0,1,0,0,0,1,1,0,0,1,0,0,0
135108,1,1,0,0,0,0,0,1,0,0,0,1,1,0,0,1,0,0,0
135108,1,1,0,0,0,0,0,1,0,0,0,1,1,0,0,1,0,0,0
135108,0,1,0,0,0,0,0,1,0,0,0,1,1,0,0,1,0,0,0
135108,1,1,0,0,0,0,0,1,0,0,0,1,1,0,0,1,0,0,0
135108,1,1,0,0,0,0,0,1,0,0,0,1,1,0,0,1,0,0,0
135108,2,1,0,0,0,0,0,1,0,0,0,1,1,0,0,1,0,0,0
135108,0,1,0,0,0,0,0,1,0,0,0,1,1,0,0,1,0,0,0
135108,1,1,0,0,0,0,0,1,0,0,0,1,1,0,0,1,0,0,0
135108,2,1,0,0,0,0,0,1,0,0,0,1,1,0,0,1,0,0,0
135109,0,0,1,0,0,0,1,0,0,0,0,1,0,1,0,1,0,0,0
135109,2,0,1,0,0,0,1,0,0,0,0,1,0,1,0,1,0,0,0
135109,1,0,1,0,0,0,1,0,0,0,0,1,0,1,0,1,0,0,0
135109,1,0,1,0,0,0,1,0,0,0,0,1,0,1,0,1,0,0,0

### Logistiline regressioon

In [29]:
df_encoded.head()

,rating,smoking_area_none,smoking_area_not permitted,smoking_area_only at bar,smoking_area_permitted,smoking_area_section,other_services_Internet,other_services_none,other_services_variety,dress_code_casual,dress_code_formal,dress_code_informal,access__completely,access__no_accessibility,access__partially,parking_none,parking_public,parking_valet parking,parking_yes
placeID,,,,,,,,,,,,,,,,,,,
132560,1,0,0,0,1,0,0,1,0,0,0,1,0,1,0,0,1,0,0
132560,0,0,0,0,1,0,0,1,0,0,0,1,0,1,0,0,1,0,0
132560,0,0,0,0,1,0,0,1,0,0,0,1,0,1,0,0,1,0,0
132560,1,0,0,0,1,0,0,1,0,0,0,1,0,1,0,0,1,0,0
132561,1,1,0,0,0,0,0,1,0,0,0,1,1,0,0,1,0,0,0

In [42]:
df_encoded.columns

Index(['rating', 'smoking_area_none', 'smoking_area_not permitted',
       'smoking_area_only at bar', 'smoking_area_permitted',
       'smoking_area_section', 'other_services_Internet',
       'other_services_none', 'other_services_variety', 'dress_code_casual',
       'dress_code_formal', 'dress_code_informal', 'access__completely',
       'access__no_accessibility', 'access__partially', 'parking_none',
       'parking_public', 'parking_valet parking', 'parking_yes'],
      dtype='object')

In [30]:
Y=df_encoded["rating"].values

In [31]:
X=df_encoded.drop("rating").values

In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegressionCV

In [33]:
logreg = LogisticRegression()

In [34]:
logreg = logreg.fit(X, y=Y)

In [35]:
X[0]

array([1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0], dtype=int64)

In [51]:
logreg._desc_= "Logistic regression model"
logreg._features_ = list(df_encoded.columns)

In [52]:
import pickle

In [53]:
#dumping model for API testing

with open("../api/model_pickles/logreg.pickle","wb") as file:
    pickle.dump(logreg, file)